language: python
python:

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"
    - web/node_modules

env:
  - PLATFORMIO_ENV=esp12e
  - PLATFORMIO_ENV=esp12e_160
  - PLATFORMIO_ENV=esp32dev

install:
  # PlatformIO
  - pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
  - platformio update
  - platformio lib install
  # install node
  - nvm install node
  - cd web && npm install && cd ..

script:
  - platformio run --environment=$PLATFORMIO_ENV
  - scripts/stylecheck
  - git diff --exit-code

before_deploy:
  - scripts/before_deploy
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: nRPmhsrR/JGGPMgknT0RX9r57XrWTLIqM6+/Twxf4uwrhkTQP5SM+Jpfuc6psViVWihrYxsrFh1kje2J12Z2ltjjex0aAlKPwjpGK7Ctbp4YZdspQpPiYH/IuNS7R4HPhC/+32rYl30m0OsFqkOmTkxHz7iykkZi/O/LTkn8QTcR2Vg5URVve8OeZtGjC0IL7te7Ove9dIlUIeb2RATpoQl29alpseyXISPhbDPqwEgkV9PeEazbxLUU7m+xflumSwWIHsF1QgBWpRIL+n93apiL3enKfXE8wCRQRVjRkF/mXeu09E0AraZNjY6AS4fIEt5ztf779hCyByw+tgS8gJLSCsB2RjUrdR6qZfW+QYxL90a0xm4dFLiYG9TMPCHUdgoM3bgLtbQW9vsCoMIsRdSD41VP9VuKcpijLRajBmFi/4LJ4HUuCI/wK56LWQLFNtw5THd88WmPvtHahQOK1QYiFufPqHL21gPVk+aZbg9vGJOFwmq/9ddGjM6ulnVMZf553XzPuLDxrOQDSyDbcaYMelsMSrEx4bLjuDb8ib9B2ah8ATALVpqGJhHgJfGySMM7zyuEFlhHT1fCnGA8IrbfS0/wkJZZoQDcr15amyI0gEefI5WUYlFhTII2901CdATjMKOpyvczi0aQnZr0ILjs84KPn1vQlmHuxiN78dc=
  file_glob: true
  file: dist/*.bin
  skip_cleanup: true
  on:
    repo: puuu/MQTT433gateway
    tags: true
